// ── Categories 2 ────────────────────────────────────────────
var cats2 = {};

// #1
cats2["Occupations"] = ["Doctor","Lawyer","Teacher","Chef","Firefighter","Police Officer","Nurse","Engineer","Architect","Pilot","Carpenter","Electrician","Plumber","Accountant","Dentist","Pharmacist","Veterinarian","Scientist","Journalist","Librarian","Mechanic","Farmer","Artist","Musician","Actor","Surgeon","Astronaut","Psychologist","Economist","Writer","Photographer","Diplomat","Judge","Professor","Soldier","Bartender","Baker","Tailor","Welder","Biologist","Chemist","Statistician","Programmer","Sailor","Philosopher"];

// #2
cats2["Countries in Asia"] = ["China","Japan","India","South Korea","North Korea","Vietnam","Thailand","Indonesia","Philippines","Malaysia","Singapore","Myanmar","Cambodia","Laos","Bangladesh","Sri Lanka","Nepal","Pakistan","Afghanistan","Iran","Iraq","Saudi Arabia","UAE","Kuwait","Qatar","Bahrain","Oman","Jordan","Israel","Lebanon","Syria","Turkey","Kazakhstan","Uzbekistan","Tajikistan","Kyrgyzstan","Turkmenistan","Mongolia","Taiwan","Bhutan","Maldives","Timor-Leste","Brunei","Armenia","Azerbaijan"];

// #3
cats2["Countries in Americas"] = ["United States","Canada","Mexico","Brazil","Argentina","Chile","Colombia","Peru","Venezuela","Ecuador","Bolivia","Paraguay","Uruguay","Cuba","Haiti","Dominican Republic","Jamaica","Trinidad and Tobago","Barbados","Bahamas","Panama","Costa Rica","Nicaragua","Honduras","El Salvador","Guatemala","Belize","Guyana","Suriname","Grenada","Saint Lucia","Saint Vincent and the Grenadines","Antigua and Barbuda","Dominica","Saint Kitts and Nevis","Aruba","Curaçao","Puerto Rico","Bermuda","Cayman Islands","Turks and Caicos","US Virgin Islands","French Guiana","Martinique","Guadeloupe"];

// #4
cats2["World Capitals"] = ["Paris","London","Berlin","Rome","Madrid","Tokyo","Beijing","New Delhi","Washington D.C.","Ottawa","Canberra","Moscow","Cairo","Nairobi","Pretoria","Buenos Aires","Brasília","Lima","Bogotá","Santiago","Mexico City","Havana","Ankara","Tehran","Baghdad","Riyadh","Bangkok","Kuala Lumpur","Jakarta","Manila","Seoul","Islamabad","Kabul","Kathmandu","Dhaka","Colombo","Ulaanbaatar","Astana","Tashkent","Warsaw","Vienna","Amsterdam","Brussels","Lisbon","Athens"];

// #5
cats2["Islands"] = ["Greenland","New Guinea","Borneo","Madagascar","Sumatra","Baffin Island","Honshu","Great Britain","Victoria Island","Ellesmere Island","Sulawesi","South Island","North Island","Cuba","Newfoundland","Luzon","Iceland","Mindanao","Ireland","Hokkaido","Hispaniola","Sakhalin","Sri Lanka","Tasmania","Timor","Hawaii","Sardinia","Sicily","Svalbard","Bali","Cyprus","Corsica","Crete","Oahu","Maui","Puerto Rico","Jamaica","Trinidad","Fiji","Malta","Maldives","Tahiti","Zanzibar","Canary Islands","Faroe Islands"];

// #6
cats2["Dinosaurs"] = ["Tyrannosaurus Rex","Velociraptor","Triceratops","Stegosaurus","Brachiosaurus","Diplodocus","Ankylosaurus","Spinosaurus","Allosaurus","Pterodactyl","Iguanodon","Pachycephalosaurus","Parasaurolophus","Apatosaurus","Compsognathus","Gallimimus","Carnotaurus","Ceratosaurus","Dilophosaurus","Archaeopteryx","Mosasaurus","Plesiosaur","Megalosaurus","Oviraptor","Therizinosaurus","Maiasaura","Edmontosaurus","Protoceratops","Deinonychus","Utahraptor","Troodon","Corythosaurus","Lambeosaurus","Styracosaurus","Baryonyx","Suchomimus","Giganotosaurus","Kentrosaurus","Pachyrhinosaurus","Psittacosaurus","Argentinosaurus","Microraptor","Abelisaurus","Hadrosaurus","Torosaurus"];

// #7
cats2["Phobias"] = ["Arachnophobia","Claustrophobia","Agoraphobia","Acrophobia","Nyctophobia","Glossophobia","Ophidiophobia","Aviophobia","Cynophobia","Trypophobia","Hemophobia","Thalassophobia","Pyrophobia","Emetophobia","Dentophobia","Necrophobia","Mysophobia","Coulrophobia","Atelophobia","Atychiphobia","Autophobia","Carcinophobia","Chronophobia","Entomophobia","Ergophobia","Gamophobia","Hippophobia","Hydrophobia","Katsaridaphobia","Ligyrophobia","Lilapsophobia","Megalophobia","Metathesiophobia","Nomophobia","Ombrophobia","Ornithophobia","Phasmophobia","Somniphobia","Trypanophobia","Xenophobia","Zoophobia","Cibophobia","Athazagoraphobia","Thanatophobia","Scopophobia"];

// #8
cats2["Marine Animals"] = ["Blue Whale","Great White Shark","Dolphin","Octopus","Sea Turtle","Manta Ray","Clownfish","Seahorse","Jellyfish","Starfish","Lobster","Crab","Shrimp","Squid","Narwhal","Manatee","Walrus","Sea Lion","Seal","Orca","Humpback Whale","Sperm Whale","Hammerhead Shark","Stingray","Barracuda","Moray Eel","Pufferfish","Anglerfish","Sea Otter","Dugong","Mantis Shrimp","Box Jellyfish","Portuguese Man o' War","Cuttlefish","Nautilus","Sea Cucumber","Horseshoe Crab","Beluga Whale","Tiger Shark","Bull Shark","Sailfish","Swordfish","Sea Snake","Oarfish","Wobbegong Shark"];

// #9
cats2["Reptiles"] = ["Komodo Dragon","Nile Crocodile","American Alligator","Green Anaconda","King Cobra","Gila Monster","Green Iguana","Chameleon","Bearded Dragon","Leopard Gecko","Tortoise","Sea Turtle","Leatherback Turtle","Snapping Turtle","Monitor Lizard","Boa Constrictor","Ball Python","Rattlesnake","Cottonmouth","Copperhead","Black Mamba","Gaboon Viper","Reticulated Python","Tuatara","Skink","Caiman","Gharial","Basilisk Lizard","Thorny Devil","Frilled Lizard","Horned Lizard","Uromastyx","Tegu","Garter Snake","Corn Snake","King Snake","Milk Snake","Vine Snake","Woma Python","Burmese Python","Sidewinder","Timber Rattlesnake","Loggerhead Sea Turtle","Blue-Tongued Skink","Flying Dragon Lizard"];

// #10
cats2["Insects"] = ["Honeybee","Monarch Butterfly","Ladybug","Dragonfly","Praying Mantis","Firefly","Grasshopper","Cricket","Cockroach","Ant","Termite","Mosquito","Housefly","Hornet","Yellow Jacket","Bumblebee","Moth","Aphid","Flea","Louse","Bed Bug","Stink Bug","Water Strider","Stick Insect","Atlas Beetle","Hercules Beetle","Rhinoceros Beetle","Stag Beetle","Dung Beetle","Tiger Beetle","June Bug","Japanese Beetle","Cicada","Earwig","Silverfish","Mayfly","Lacewing","Weevil","Caterpillar","Leafcutter Ant","Fire Ant","Whirligig Beetle","Assassin Bug","Mantisfly","Dobsonfly"];

// #11
cats2["Saltwater Fish"] = ["Clownfish","Blue Tang","Angelfish","Lionfish","Parrotfish","Triggerfish","Grouper","Snapper","Mahi-Mahi","Tuna","Swordfish","Marlin","Sailfish","Barracuda","Amberjack","Sea Bass","Halibut","Flounder","Cod","Haddock","Mackerel","Sardine","Anchovy","Herring","Bluefish","Pompano","Wahoo","Cobia","Tarpon","Bonefish","Permit","Red Drum","Striped Bass","Sheepshead","Porgy","Sea Bream","Wrasse","Damselfish","Goby","Blenny","Hawkfish","Pufferfish","Surgeonfish","Flying Fish","Moray Eel"];

// #12
cats2["Freshwater Fish"] = ["Largemouth Bass","Smallmouth Bass","Rainbow Trout","Brown Trout","Brook Trout","Lake Trout","Chinook Salmon","Coho Salmon","Atlantic Salmon","Walleye","Northern Pike","Muskellunge","Catfish","Channel Catfish","Bluegill","Crappie","Yellow Perch","Carp","Goldfish","Koi","Tilapia","Guppy","Betta Fish","Freshwater Angelfish","Oscar","Cichlid","Discus","Piranha","Arapaima","Electric Eel","Sturgeon","Paddlefish","Gar","Bowfin","American Shad","Freshwater Drum","Sunfish","Pumpkinseed","Redear Sunfish","Rock Bass","White Bass","Sauger","Burbot","Zander","Roach"];

// #13
cats2["Spices and Herbs"] = ["Basil","Oregano","Thyme","Rosemary","Sage","Parsley","Cilantro","Dill","Chives","Mint","Tarragon","Bay Leaf","Marjoram","Lavender","Cumin","Coriander","Turmeric","Paprika","Cayenne","Chili Powder","Black Pepper","White Pepper","Cinnamon","Nutmeg","Cloves","Cardamom","Ginger","Fennel","Star Anise","Anise","Caraway","Saffron","Sumac","Za'atar","Fenugreek","Mustard Seed","Celery Seed","Allspice","Mace","Juniper Berry","Lemongrass","Galangal","Asafoetida","Vanilla","Horseradish"];

// #14
cats2["Fast Food Chains"] = ["McDonald's","Burger King","Wendy's","Taco Bell","KFC","Chick-fil-A","Subway","Pizza Hut","Domino's","Papa John's","Popeyes","Panda Express","Chipotle","Sonic","Arby's","Jack in the Box","White Castle","Five Guys","In-N-Out Burger","Shake Shack","Culver's","Whataburger","Carl's Jr.","Hardee's","Del Taco","Wingstop","Raising Cane's","Zaxby's","Steak 'n Shake","Waffle House","IHOP","Denny's","Cracker Barrel","Panera Bread","Quiznos","Jersey Mike's","Jimmy John's","Firehouse Subs","Bojangles","Church's Chicken","Long John Silver's","Dairy Queen","Little Caesars","Checkers","Noodles & Company"];

// #15
cats2["Ice Cream Flavors"] = ["Vanilla","Chocolate","Strawberry","Mint Chocolate Chip","Cookies and Cream","Rocky Road","Butter Pecan","Cookie Dough","Neapolitan","Pistachio","Pralines and Cream","Peach","Cherry Garcia","Phish Food","Chunky Monkey","Coffee","Caramel","Salted Caramel","Rum Raisin","Bubble Gum","Cotton Candy","Rainbow Sherbet","Lemon Sorbet","Mango","Coconut","Banana","Black Raspberry","Blueberry","Peanut Butter","Peanut Butter Cup","S'mores","Birthday Cake","Red Velvet","Cinnamon","Eggnog","Pumpkin Spice","Matcha","Lavender","Honey","Maple","Superman","Spumoni","Tutti Frutti","Tiger Stripe","Moose Tracks"];

// #16
cats2["Vegetables"] = ["Carrot","Broccoli","Spinach","Kale","Lettuce","Tomato","Cucumber","Bell Pepper","Onion","Garlic","Potato","Sweet Potato","Corn","Peas","Green Beans","Asparagus","Celery","Cauliflower","Cabbage","Brussels Sprouts","Zucchini","Squash","Pumpkin","Eggplant","Beet","Radish","Turnip","Parsnip","Leek","Artichoke","Fennel","Swiss Chard","Bok Choy","Arugula","Endive","Watercress","Kohlrabi","Jicama","Cassava","Taro","Okra","Mushroom","Avocado","Yam","Shallot"];

// #17
cats2["Card Games"] = ["Poker","Blackjack","Solitaire","Go Fish","Rummy","Gin Rummy","Bridge","Canasta","Cribbage","Spades","Hearts","War","Old Maid","Crazy Eights","Snap","Uno","Skip-Bo","Phase 10","Rook","Euchre","Pinochle","Whist","Slapjack","Egyptian Rat Screw","Concentration","Speed","Palace","Sevens","Kings Corner","Baccarat","Piquet","Bezique","Skat","Kalooki","Spite and Malice","Tonk","Durak","Tichu","Hanabi","Exploding Kittens","Coup","Love Letter","Dobble","Taco Cat Goat Cheese Pizza","Sushi Go"];

// #18
cats2["Board Games"] = ["Monopoly","Scrabble","Chess","Checkers","Risk","Clue","Battleship","Connect Four","Othello","The Game of Life","Sorry!","Candy Land","Chutes and Ladders","Trivial Pursuit","Jenga","Pictionary","Taboo","Cranium","Pandemic","Settlers of Catan","Ticket to Ride","Carcassonne","Dominion","Agricola","Terraforming Mars","Azul","7 Wonders","Splendor","Codenames","Dixit","Mysterium","Betrayal at House on the Hill","Arkham Horror","Gloomhaven","Wingspan","Everdell","Root","Twilight Imperium","Diplomacy","Puerto Rico","Stratego","Backgammon","Mahjong","Sequence","Power Grid"];

// #19
cats2["Nintendo Games"] = ["Super Mario Bros.","The Legend of Zelda: Ocarina of Time","Pokémon Red/Blue","Donkey Kong","Metroid","Kirby's Dream Land","Star Fox","F-Zero","Punch-Out!!","Super Smash Bros.","Mario Kart 64","GoldenEye 007","The Legend of Zelda: A Link to the Past","Super Metroid","Super Mario World","Yoshi's Island","EarthBound","Fire Emblem","Animal Crossing","Pikmin","Splatoon","Wii Sports","Super Mario Odyssey","Breath of the Wild","Tears of the Kingdom","Mario Party","Paper Mario","Luigi's Mansion","Xenoblade Chronicles","Kid Icarus","Duck Hunt","Excitebike","Ice Climber","Balloon Fight","Castlevania","Mega Man","Tetris","Pokémon Yellow","Mario Golf","Mario Tennis","Arms","Ring Fit Adventure","Wii Fit","Banjo-Kazooie","Majora's Mask"];

// #20
cats2["PlayStation Games"] = ["God of War","The Last of Us","Uncharted","Horizon Zero Dawn","Spider-Man","Ghost of Tsushima","Gran Turismo","Crash Bandicoot","Spyro the Dragon","Ratchet & Clank","Jak and Daxter","Sly Cooper","Shadow of the Colossus","Ico","Bloodborne","Demon's Souls","Final Fantasy VII","Final Fantasy X","Kingdom Hearts","Metal Gear Solid","Resident Evil 2","Silent Hill","Tomb Raider","Grand Theft Auto: San Andreas","Tekken","Twisted Metal","Wipeout","Infamous","Killzone","Resistance","LittleBigPlanet","Astro's Playroom","Returnal","Nioh","Death Stranding","Days Gone","Detroit: Become Human","Heavy Rain","Until Dawn","Dreams","Sekiro","Mortal Kombat","Ape Escape","MediEvil","SOCOM"];

// #21
cats2["Classic Arcade Games"] = ["Pac-Man","Donkey Kong","Space Invaders","Galaga","Asteroids","Centipede","Missile Command","Frogger","Defender","Tempest","Dig Dug","Tron","Q*bert","Joust","Robotron: 2084","Zaxxon","Pengo","Burger Time","Moon Patrol","Spy Hunter","Paperboy","Gauntlet","Double Dragon","Contra","Street Fighter II","Mortal Kombat","Final Fight","Golden Axe","Altered Beast","Time Crisis","House of the Dead","Operation Wolf","Rampage","TMNT","X-Men","The Simpsons Arcade","Tekken","Virtua Fighter","Area 51","Pong","Breakout","Phoenix","Battlezone","Star Wars","Crystal Castles"];

// #22
cats2["Horror Movie Monsters"] = ["Dracula","Frankenstein's Monster","The Wolfman","The Mummy","Creature from the Black Lagoon","The Invisible Man","Freddy Krueger","Jason Voorhees","Michael Myers","Leatherface","Pinhead","Chucky","Ghostface","Pennywise","The Xenomorph","The Predator","The Thing","Jaws","King Kong","Godzilla","Annabelle","The Babadook","Samara","The Demogorgon","The Nun","Kayako","Pumpkinhead","Candyman","Pazuzu","The Pale Man","The Grabber","The Creeper","Pyramid Head","Count Orlok","The Blob","Cloverfield Monster","The Blair Witch","Mama","The Headless Horseman","The Wendigo","Slender Man","The Rake","The Witch","The Shape","It"];

// #23
cats2["Fictional Detectives"] = ["Sherlock Holmes","Hercule Poirot","Miss Marple","Sam Spade","Philip Marlowe","Perry Mason","Columbo","Inspector Morse","Jessica Fletcher","Vera Stanhope","Easy Rawlins","V.I. Warshawski","Kinsey Millhone","Dave Robicheaux","Harry Bosch","Mma Ramotswe","Brother Cadfael","Albert Campion","Lord Peter Wimsey","Inspector Wexford","Inspector Banks","Thomas Lynley","Adam Dalgliesh","Richard Jury","Lisbeth Salander","Veronica Mars","Spencer","Travis McGee","Nick Charles","Nero Wolfe","Ellery Queen","Philo Vance","Cormoran Strike","Benoit Blanc","Adrian Monk","Patrick Jane","Temperance Brennan","Fox Mulder","Kurt Wallander","Endeavour Morse","DCI Jane Tennison","Kay Scarpetta","Alex Delaware","Lincoln Rhyme","Jack Reacher"];

// #24
cats2["Fictional Villains"] = ["Darth Vader","The Joker","Hannibal Lecter","Lex Luthor","Voldemort","Sauron","Thanos","Loki","Magneto","Doctor Doom","Iago","Captain Hook","Moriarty","Ernst Stavro Blofeld","Hans Gruber","Anton Chigurh","Annie Wilkes","Norman Bates","Patrick Bateman","Amy Dunne","Nurse Ratched","Alex DeLarge","Frank Underwood","Walter White","Tony Soprano","Cersei Lannister","Joffrey Baratheon","Emperor Palpatine","Ursula","Maleficent","Cruella de Vil","Gaston","Jafar","Scar","Hades","Gollum","Saruman","Keyser Söze","Judge Doom","Dolores Umbridge","Count Rugen","Randall Flagg","The Corinthian","Roy Batty","HAL 9000"];

// #25
cats2["Dystopian Novels"] = ["1984","Brave New World","The Handmaid's Tale","Fahrenheit 451","The Road","A Clockwork Orange","Lord of the Flies","Animal Farm","We","The Giver","Divergent","The Hunger Games","Catching Fire","Mockingjay","The Maze Runner","Matched","Delirium","Legend","Red Rising","Station Eleven","The Children of Men","Oryx and Crake","Never Let Me Go","The Iron Heel","Anthem","Ender's Game","Parable of the Sower","The Power","The Circle","Feed","Little Brother","Wool","The Passage","Alas Babylon","On the Beach","Riddley Walker","MaddAddam","The Year of the Flood","Super Sad True Love Story","Jennifer Government","The Dispossessed","Swan Song","The Windup Girl","Scythe","The Memory Police"];

// #26
cats2["Animated Disney Characters"] = ["Mickey Mouse","Minnie Mouse","Donald Duck","Goofy","Pluto","Daisy Duck","Bambi","Dumbo","Pinocchio","Cinderella","Snow White","Aurora","Ariel","Belle","Jasmine","Mulan","Pocahontas","Tiana","Rapunzel","Merida","Moana","Simba","Timon","Pumbaa","Mufasa","Aladdin","Genie","Lumiere","Cogsworth","Flounder","Sebastian","Stitch","Nemo","Dory","Woody","Buzz Lightyear","Elsa","Anna","Olaf","Wall-E","Eve","Remy","Hercules","Quasimodo","Tarzan"];

// #27
cats2["Westerns"] = ["The Good the Bad and the Ugly","Once Upon a Time in the West","High Noon","Shane","Stagecoach","Red River","The Searchers","Rio Bravo","Tombstone","Unforgiven","Butch Cassidy and the Sundance Kid","True Grit","The Magnificent Seven","A Fistful of Dollars","For a Few Dollars More","Pale Rider","The Outlaw Josey Wales","Dances with Wolves","Open Range","3:10 to Yuma","Django Unchained","The Hateful Eight","Bone Tomahawk","Jeremiah Johnson","McCabe & Mrs. Miller","Little Big Man","Blazing Saddles","Silverado","Wyatt Earp","Dead Man","The Assassination of Jesse James","The Power of the Dog","News of the World","Hell or High Water","Wind River","Hostiles","Lonesome Dove","No Country for Old Men","There Will Be Blood","Pat Garrett and Billy the Kid","The Wild Bunch","El Dorado","Ride the High Country","Destry Rides Again","The Revenant"];

// #28
cats2["90s Movies"] = ["Titanic","Schindler's List","Pulp Fiction","The Silence of the Lambs","Goodfellas","Jurassic Park","The Shawshank Redemption","Forrest Gump","The Lion King","Home Alone","Toy Story","Aladdin","The Matrix","Fight Club","American Beauty","Seven","L.A. Confidential","Braveheart","Saving Private Ryan","The Sixth Sense","Groundhog Day","Mrs. Doubtfire","The Truman Show","Trainspotting","Fargo","Boogie Nights","Heat","The Usual Suspects","Speed","Scream","Clueless","Dumb and Dumber","Ace Ventura","The Mask","Liar Liar","Billy Madison","Happy Gilmore","Wayne's World","Terminator 2","Home Alone 2","Casino","American History X","Magnolia","Carlito's Way","Die Hard with a Vengeance"];

// #29
cats2["2020s Movies"] = ["Everything Everywhere All at Once","Oppenheimer","Barbie","Top Gun: Maverick","Spider-Man: No Way Home","Avatar: The Way of Water","The Batman","Dune","Dune: Part Two","No Time to Die","Tenet","The Power of the Dog","Belfast","CODA","Encanto","Turning Red","The Suicide Squad","Shang-Chi","Eternals","Black Widow","Promising Young Woman","Nomadland","Sound of Metal","The Trial of the Chicago 7","Free Guy","Ghostbusters: Afterlife","West Side Story","Wrath of Man","Black Panther: Wakanda Forever","Doctor Strange in the Multiverse of Madness","Thor: Love and Thunder","Elvis","Bullet Train","The Northman","Decision to Leave","Aftersun","The Whale","Tár","All Quiet on the Western Front","The Fabelmans","Beau Is Afraid","Past Lives","Killers of the Flower Moon","Poor Things","American Fiction"];

// #30
cats2["90s Sitcoms"] = ["Friends","Seinfeld","Frasier","Home Improvement","Roseanne","The Fresh Prince of Bel-Air","Full House","Family Matters","Step by Step","Boy Meets World","Saved by the Bell","Living Single","Martin","Mad About You","Ellen","Everybody Loves Raymond","3rd Rock from the Sun","NewsRadio","Wings","Coach","Murphy Brown","Married with Children","The Nanny","Grace Under Fire","Sister Sister","Moesha","Hanging with Mr. Cooper","The Wayans Bros.","Kenan & Kel","Clarissa Explains It All","Spin City","Dharma & Greg","Just Shoot Me!","Blossom","Party of Five","My So-Called Life","Dinosaurs","Empty Nest","Golden Girls","Cheers","In Living Color","Will & Grace","Dave's World","Cybill","Roc"];

// #31
cats2["Reality TV Shows"] = ["Survivor","The Amazing Race","Big Brother","American Idol","The Voice","Dancing with the Stars","America's Got Talent","The Bachelor","The Bachelorette","Love Island","Married at First Sight","Too Hot to Handle","The Real World","Jersey Shore","Keeping Up with the Kardashians","Real Housewives of New York City","Real Housewives of Atlanta","Real Housewives of Beverly Hills","Vanderpump Rules","Below Deck","Project Runway","America's Next Top Model","RuPaul's Drag Race","Hell's Kitchen","Top Chef","MasterChef","Chopped","The Great British Bake Off","Cake Boss","Fixer Upper","Property Brothers","Trading Spaces","What Not to Wear","Queer Eye","Fear Factor","Jackass","Punk'd","Catfish","My Strange Addiction","Hoarders","Intervention","Dog the Bounty Hunter","Deadliest Catch","Cops","The Apprentice"];

// #32
cats2["YouTubers"] = ["PewDiePie","MrBeast","Markiplier","Jacksepticeye","VanossGaming","DanTDM","Lilly Singh","Smosh","Ryan's World","Dude Perfect","Like Nastya","Dhar Mann","Jeffree Star","James Charles","NikkieTutorials","Emma Chamberlain","David Dobrik","Jake Paul","Logan Paul","KSI","Sidemen","Ninja","Pokimane","Valkyrae","SSSniperWolf","Liza Koshy","Philip DeFranco","CGP Grey","Kurzgesagt","Vsauce","Veritasium","SmarterEveryDay","Mark Rober","Good Mythical Morning","Jenna Marbles","Colleen Ballinger","Hank Green","Film Theory","LinusTechTips","Tom Scott","Numberphile","Wendover Productions","Corridor Crew","Internet Comment Etiquette","Tana Mongeau"];

// #33
cats2["One-Hit Wonders"] = ["Mambo No. 5 – Lou Bega","Who Let the Dogs Out – Baha Men","Gangnam Style – PSY","Macarena – Los Del Rio","Tubthumping – Chumbawamba","Ice Ice Baby – Vanilla Ice","Come On Eileen – Dexys Midnight Runners","Take On Me – a-ha","I'm Too Sexy – Right Said Fred","Breakfast at Tiffany's – Deep Blue Something","What Is Love – Haddaway","Cotton Eye Joe – Rednex","Barbie Girl – Aqua","Video Killed the Radio Star – The Buggles","Tainted Love – Soft Cell","Pass the Dutchie – Musical Youth","Kung Fu Fighting – Carl Douglas","In the Summertime – Mungo Jerry","Spirit in the Sky – Norman Greenbaum","Stay – Lisa Loeb","Closing Time – Semisonic","Flagpole Sitta – Harvey Danger","Baby Got Back – Sir Mix-a-Lot","Informer – Snow","Whoomp! (There It Is) – Tag Team","Jump – Kris Kross","Somebody That I Used to Know – Gotye","Numa Numa – O-Zone","Friday – Rebecca Black","What Does the Fox Say? – Ylvis","Chocolate Rain – Tay Zonday","Bad Day – Daniel Powter","Butterfly – Crazy Town","How Bizarre – OMC","Steal My Sunshine – Len","Mickey – Toni Basil","Der Kommissar – After the Fire","99 Luftballons – Nena","Just Like Heaven – The Cure","I'd Do Anything for Love – Meat Loaf","How Do I Live – LeAnn Rimes","Lovefool – The Cardigans","One Week – Barenaked Ladies","Brimful of Asha – Cornershop","Walkin' on the Sun – Smash Mouth"];

// #34
cats2["Hip Hop Artists"] = ["Jay-Z","Kendrick Lamar","Eminem","Nas","Tupac Shakur","The Notorious B.I.G.","Dr. Dre","Snoop Dogg","Kanye West","Lil Wayne","Drake","Nicki Minaj","Cardi B","Travis Scott","J. Cole","A$AP Rocky","Tyler the Creator","Chance the Rapper","Childish Gambino","Wiz Khalifa","Future","Young Thug","Migos","21 Savage","Lil Baby","Post Malone","Juice WRLD","Lil Uzi Vert","Ice Cube","Ice-T","Public Enemy","Wu-Tang Clan","Outkast","Missy Elliott","Queen Latifah","Salt-N-Pepa","MC Hammer","Beastie Boys","Big Pun","Big L","MF DOOM","Rakim","Big Daddy Kane","DMX","Run-DMC"];

// #35
cats2["Country Music Artists"] = ["Garth Brooks","Dolly Parton","Willie Nelson","Johnny Cash","Hank Williams","Patsy Cline","Loretta Lynn","George Strait","Alan Jackson","Tim McGraw","Faith Hill","Shania Twain","Kenny Rogers","Reba McEntire","Trisha Yearwood","Brooks & Dunn","Dwight Yoakam","Brad Paisley","Keith Urban","Dierks Bentley","Eric Church","Luke Bryan","Jason Aldean","Blake Shelton","Miranda Lambert","Carrie Underwood","Taylor Swift","Kacey Musgraves","Maren Morris","Chris Stapleton","Sturgill Simpson","Tyler Childers","Morgan Wallen","Luke Combs","Kane Brown","Thomas Rhett","Sam Hunt","Zac Brown Band","Lady A","Little Big Town","Kenny Chesney","Toby Keith","Trace Adkins","George Jones","Merle Haggard"];

// #36
cats2["Famous DJs"] = ["DJ Khaled","Tiësto","Calvin Harris","David Guetta","Martin Garrix","Avicii","Deadmau5","Skrillex","Diplo","Marshmello","Steve Aoki","Armin van Buuren","Hardwell","Afrojack","Kygo","Zedd","DJ Snake","Daft Punk","The Chainsmokers","Flume","Porter Robinson","Madeon","Disclosure","Odesza","Fred Again","John Summit","Fisher","Chris Lake","Green Velvet","Carl Cox","Richie Hawtin","Pete Tong","Paul Oakenfold","Fatboy Slim","Chemical Brothers","Moby","Basement Jaxx","DJ Premier","DJ Shadow","J Dilla","Grandmaster Flash","Afrika Bambaataa","DJ Jazzy Jeff","Major Lazer","Four Tet"];

// #37
cats2["Figures of Speech"] = ["Metaphor","Simile","Personification","Alliteration","Hyperbole","Irony","Sarcasm","Euphemism","Oxymoron","Paradox","Anaphora","Antithesis","Allusion","Apostrophe","Assonance","Consonance","Onomatopoeia","Synecdoche","Metonymy","Litotes","Understatement","Chiasmus","Epistrophe","Asyndeton","Polysyndeton","Ellipsis","Enjambment","Climax","Anticlimax","Zeugma","Pun","Malapropism","Spoonerism","Catachresis","Hypophora","Rhetorical Question","Anachronism","Tautology","Pleonasm","Circumlocution","Periphrasis","Anadiplosis","Diacope","Antanaclasis","Symploce"];

// #38
cats2["Languages of the World"] = ["Mandarin Chinese","Spanish","English","Hindi","Arabic","Portuguese","Bengali","Russian","Japanese","Punjabi","German","French","Urdu","Korean","Telugu","Vietnamese","Marathi","Tamil","Turkish","Italian","Gujarati","Thai","Persian","Polish","Pashto","Kannada","Indonesian","Malay","Swahili","Dutch","Romanian","Ukrainian","Greek","Czech","Hungarian","Swedish","Hebrew","Finnish","Norwegian","Danish","Tagalog","Burmese","Sinhalese","Amharic","Hausa"];

// #39
cats2["Narrative Techniques"] = ["First-person narration","Third-person omniscient","Third-person limited","Second-person narration","Unreliable narrator","Stream of consciousness","Flashback","Flash-forward","In medias res","Foreshadowing","Dramatic irony","Situational irony","Verbal irony","Cliffhanger","Deus ex machina","Red herring","Chekhov's Gun","Epistolary format","Frame narrative","Multiple perspectives","Nonlinear structure","Circular narrative","Free indirect discourse","Interior monologue","Exposition","Rising action","Climax","Falling action","Denouement","Subplot","Motif","Leitmotif","Symbolism","Allegory","Pathetic fallacy","MacGuffin","Dramatic monologue","Soliloquy","Parallel narrative","Braided narrative","Nested narrative","Reverse chronology","Magical realism","Metafiction","Prolepsis"];

// #40
cats2["Fairy Tales"] = ["Cinderella","Snow White","Sleeping Beauty","Rapunzel","Little Red Riding Hood","Hansel and Gretel","Rumpelstiltskin","Jack and the Beanstalk","Goldilocks and the Three Bears","The Three Little Pigs","The Ugly Duckling","The Little Mermaid","Thumbelina","The Snow Queen","The Princess and the Pea","The Emperor's New Clothes","The Pied Piper of Hamelin","Tom Thumb","Beauty and the Beast","The Frog Prince","Puss in Boots","The Boy Who Cried Wolf","The Tortoise and the Hare","The Ant and the Grasshopper","Ali Baba and the Forty Thieves","Aladdin","Sinbad the Sailor","The Six Swans","East of the Sun West of the Moon","Bluebeard","Mother Holle","The Twelve Dancing Princesses","The Wild Swans","The Little Match Girl","The Steadfast Tin Soldier","The Red Shoes","The Nightingale","Donkeyskin","Maid Maleen","Iron John","The Juniper Tree","The Goose Girl","Allerleirauh","Fitcher's Bird","Snow White and Rose Red"];

// #41
cats2["Mythological Creatures"] = ["Dragon","Unicorn","Phoenix","Griffin","Chimera","Minotaur","Centaur","Medusa","Hydra","Cerberus","Sphinx","Pegasus","Kraken","Cyclops","Harpy","Siren","Mermaid","Manticore","Basilisk","Wyvern","Vampire","Werewolf","Zombie","Banshee","Leprechaun","Faerie","Troll","Goblin","Ogre","Gnome","Satyr","Nymph","Incubus","Succubus","Kitsune","Tengu","Tanuki","Oni","Selkie","Kelpie","Naga","Rakshasa","Yeti","Cockatrice","Thunderbird"];

// #42
cats2["Greek Gods and Goddesses"] = ["Zeus","Hera","Poseidon","Demeter","Athena","Apollo","Artemis","Ares","Aphrodite","Hephaestus","Hermes","Dionysus","Hades","Persephone","Hestia","Eros","Psyche","Helios","Selene","Eos","Nemesis","Tyche","Nike","Iris","Hecate","Morpheus","Hypnos","Thanatos","Charon","Cronus","Rhea","Gaia","Uranus","Prometheus","Epimetheus","Atlas","Hercules","Perseus","Theseus","Achilles","Odysseus","Orpheus","Medea","Circe","Calypso"];

// #43
cats2["Olympic Sports"] = ["Swimming","Gymnastics","Pentathlon","Diving","Wrestling","Rowing","Boxing","Soccer","Judo","Archery","Tennis","Volleyball","Weightlifting","Skateboarding","Triathlon","Badminton","Fencing","Sailing","Surfing","Equestrian","Water Polo","Field Hockey","Basketball","Bicycling","Karate","Ice Hockey","Lacrosse","Baseball","Biathlon","Table Tennis","Figure Skating","Golf","Bobsleigh","Shooting","Cricket","Curling","Luge","Canoeing","Football","Rugby Sevens","Softball","Taekwondo","Squash","Sport Climbing","Skiing"];

// #44
cats2["80s Pop Hits"] = ["Take On Me – a-ha","Don't You (Forget About Me) – Simple Minds","Walking on Sunshine – Katrina and the Waves","Girls Just Want to Have Fun – Cyndi Lauper","Like a Prayer – Madonna","Material Girl – Madonna","Sweet Child O' Mine – Guns N' Roses","Every Breath You Take – The Police","Billie Jean – Michael Jackson","Beat It – Michael Jackson","Thriller – Michael Jackson","Jump – Van Halen","Wake Me Up Before You Go-Go – Wham!","Careless Whisper – George Michael","Don't Stop Believin' – Journey","Livin' on a Prayer – Bon Jovi","Born in the U.S.A. – Bruce Springsteen","Purple Rain – Prince","When Doves Cry – Prince","Total Eclipse of the Heart – Bonnie Tyler","I Want to Know What Love Is – Foreigner","Eye of the Tiger – Survivor","The Final Countdown – Europe","Come On Eileen – Dexys Midnight Runners","99 Luftballons – Nena","Tainted Love – Soft Cell","Rio – Duran Duran","Africa – Toto","True – Spandau Ballet","Karma Chameleon – Culture Club","How Soon Is Now? – The Smiths","Bizarre Love Triangle – New Order","Blue Monday – New Order","Love Will Tear Us Apart – Joy Division","Everybody Wants to Rule the World – Tears for Fears","Don't You Want Me – Human League","Here I Go Again – Whitesnake","Rock You Like a Hurricane – Scorpions","Just Like Heaven – The Cure","Boys of Summer – Don Henley","Sister Christian – Night Ranger","Jessie's Girl – Rick Springfield","Der Kommissar – After the Fire","Hungry Like the Wolf – Duran Duran","We Built This City – Starship"];

// #45
cats2["Anime Series"] = ["Dragon Ball Z","Naruto","One Piece","Bleach","Attack on Titan","Fullmetal Alchemist: Brotherhood","Death Note","Sword Art Online","My Hero Academia","Demon Slayer","Jujutsu Kaisen","Hunter x Hunter","Yu Yu Hakusho","Cowboy Bebop","Neon Genesis Evangelion","Ghost in the Shell","Sailor Moon","Cardcaptor Sakura","Inuyasha","Rurouni Kenshin","Trigun","Outlaw Star","Digimon","Pokémon","Yu-Gi-Oh!","Fairy Tail","Black Clover","Haikyuu!!","Violet Evergarden","Your Lie in April","Clannad","Re:Zero","No Game No Life","Code Geass","Steins;Gate","Overlord","That Time I Got Reincarnated as a Slime","Tokyo Ghoul","Black Butler","One Punch Man","Mob Psycho 100","Assassination Classroom","The Rising of the Shield Hero","Spirited Away","Fullmetal Alchemist (2003)"];
